export const mockFriends = [
    {
        id: 1,
        avatar: 'https://robohash.org/nisiestnesciunt.jpg?size=50x50&set=set1',
        username: 'pguice0',
        status: 4,
    },
    {
        id: 2,
        avatar: 'https://robohash.org/quiauteum.jpg?size=50x50&set=set5',
        username: 'lmcnally1',
        status: 2,
    },
    {
        id: 3,
        avatar: 'https://robohash.org/expeditaipsasunt.jpg?size=50x50&set=set5',
        username: 'driddick2',
        status: 4,
    },
    {
        id: 4,
        avatar: 'https://robohash.org/explicabolaborecommodi.jpg?size=50x50&set=set5',
        username: 'tgiovanetti3',
        status: 2,
    },
    {
        id: 5,
        avatar: 'https://robohash.org/officiisdictatempora.jpg?size=50x50&set=set5',
        username: 'mnormavell4',
        status: 1,
    },
    {
        id: 6,
        avatar: 'https://robohash.org/accusantiumnequeconsequatur.jpg?size=50x50&set=set1',
        username: 'bduplain5',
        status: 3,
    },
    {
        id: 7,
        avatar: 'https://robohash.org/magnietomnis.jpg?size=50x50&set=set5',
        username: 'bnoirel6',
        status: 4,
    },
    {
        id: 8,
        avatar: 'https://robohash.org/dignissimosminuscum.jpg?size=50x50&set=set5',
        username: 'krangle7',
        status: 2,
    },
    {
        id: 9,
        avatar: 'https://robohash.org/ipsamdistinctioqui.jpg?size=50x50&set=set2',
        username: 'hillston8',
        status: 2,
    },
    {
        id: 10,
        avatar: 'https://robohash.org/iustoevenietbeatae.jpg?size=50x50&set=set5',
        username: 'aleteve9',
        status: 3,
    },
    {
        id: 11,
        avatar: 'https://robohash.org/aliasconsequaturveniam.jpg?size=50x50&set=set2',
        username: 'aocassidya',
        status: 4,
    },
    {
        id: 12,
        avatar: 'https://robohash.org/voluptatemliberoreiciendis.jpg?size=50x50&set=set5',
        username: 'tcourceyb',
        status: 1,
    },
    {
        id: 13,
        avatar: 'https://robohash.org/veniamsuscipitqui.jpg?size=50x50&set=set1',
        username: 'anibloec',
        status: 4,
    },
    {
        id: 14,
        avatar: 'https://robohash.org/doloribuscumnon.jpg?size=50x50&set=set5',
        username: 'nleyesd',
        status: 3,
    },
    {
        id: 15,
        avatar: 'https://robohash.org/quisvoluptatemid.jpg?size=50x50&set=set5',
        username: 'bcarltone',
        status: 4,
    },
    {
        id: 16,
        avatar: 'https://robohash.org/consequunturpariatursapiente.jpg?size=50x50&set=set5',
        username: 'dcartmaelf',
        status: 1,
    },
    {
        id: 17,
        avatar: 'https://robohash.org/asperioresinventorenihil.jpg?size=50x50&set=set1',
        username: 'hbellhamg',
        status: 1,
    },
    {
        id: 18,
        avatar: 'https://robohash.org/porrocommodicorporis.jpg?size=50x50&set=set5',
        username: 'tcaplinh',
        status: 1,
    },
    {
        id: 19,
        avatar: 'https://robohash.org/teneturnequenostrum.jpg?size=50x50&set=set1',
        username: 'gmeegini',
        status: 1,
    },
    {
        id: 20,
        avatar: 'https://robohash.org/aliasexpeditaminima.jpg?size=50x50&set=set5',
        username: 'bbrendej',
        status: 2,
    },
]
